// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyAA8jXYuQM8QlQ3vH67xd4zimYnXRALANw',
    // appId: '1:520182917938:web:3e7614063be33e7c1f452b',
    // messagingSenderId: '520182917938',
    // projectId: 'collecta-125aa',
    // authDomain: 'collecta-125aa.firebaseapp.com',
    // storageBucket: 'collecta-125aa.firebasestorage.app',
    // measurementId: 'G-M4801X6VYK',



    apiKey: "AIzaSyCniLqCqQaWLPVn1qmqz08K92_xtRYb_k0",
    authDomain: "collecta-125aa.firebaseapp.com",
    projectId: "collecta-125aa",
    storageBucket: "collecta-125aa.firebasestorage.app",
    messagingSenderId: "520182917938",
    appId: "1:520182917938:web:f54504e433d782bf1f452b",
    measurementId: "G-YZ3BCN4MVT",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARA8lE2koZRK7G3PmMdy_J_MGXrb2gLA',
    appId: '1:520182917938:android:ae4b3a5de69efc051f452b',
    messagingSenderId: '520182917938',
    projectId: 'collecta-125aa',
    storageBucket: 'collecta-125aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACLd-ElNI0smjKvd7Y2L7o-n8x1mnrtfw',
    appId: '1:520182917938:ios:b207e07fb618c9ee1f452b',
    messagingSenderId: '520182917938',
    projectId: 'collecta-125aa',
    storageBucket: 'collecta-125aa.firebasestorage.app',
    iosClientId: '520182917938-s7c5k1u8ec6fmmjjugjbp5l8k8h8c549.apps.googleusercontent.com',
    iosBundleId: 'com.example.collecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACLd-ElNI0smjKvd7Y2L7o-n8x1mnrtfw',
    appId: '1:520182917938:ios:b207e07fb618c9ee1f452b',
    messagingSenderId: '520182917938',
    projectId: 'collecta-125aa',
    storageBucket: 'collecta-125aa.firebasestorage.app',
    iosClientId: '520182917938-s7c5k1u8ec6fmmjjugjbp5l8k8h8c549.apps.googleusercontent.com',
    iosBundleId: 'com.example.collecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA8jXYuQM8QlQ3vH67xd4zimYnXRALANw',
    appId: '1:520182917938:web:704a68b40824064d1f452b',
    messagingSenderId: '520182917938',
    projectId: 'collecta-125aa',
    authDomain: 'collecta-125aa.firebaseapp.com',
    storageBucket: 'collecta-125aa.firebasestorage.app',
    measurementId: 'G-DW01V1V9WK',
  );
}
